"""create core tables

Revision ID: 4b5a42df95a7
Revises: 
Create Date: 2026-10-01 23:01:02.083520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5a42df95a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('notify_parent_on_correction', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_table('guardians',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("substr(phone, 1, 1) = '+'", name=op.f('ck_guardians_phone_e164_prefix')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_guardians_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardians')),
    sa.UniqueConstraint('school_id', 'id', name=op.f('uq_guardians_school_id'))
    )
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardians_school_id'), ['school_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('class_name', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_students_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('school_id', 'id', name=op.f('uq_students_school_id'))
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_school_id'), ['school_id'], unique=False)

    op.create_table('student_guardians',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id', 'guardian_id'], ['guardians.school_id', 'guardians.id'], name=op.f('fk_student_guardians_school_id_guardians')),
    sa.ForeignKeyConstraint(['school_id', 'student_id'], ['students.school_id', 'students.id'], name=op.f('fk_student_guardians_school_id_students')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_student_guardians_school_id_schools')),
    sa.PrimaryKeyConstraint('student_id', 'guardian_id', name=op.f('pk_student_guardians'))
    )
    with op.batch_alter_table('student_guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_guardians_school_id'), ['school_id'], unique=False)
        batch_op.create_index('uq_student_guardians_one_primary', ['student_id'], unique=True, sqlite_where=sa.text('is_primary'), postgresql_where=sa.text('is_primary'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_guardians', schema=None) as batch_op:
        batch_op.drop_index('uq_student_guardians_one_primary', sqlite_where=sa.text('is_primary'), postgresql_where=sa.text('is_primary'))
        batch_op.drop_index(batch_op.f('ix_student_guardians_school_id'))

    op.drop_table('student_guardians')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_school_id'))

    op.drop_table('students')
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardians_school_id'))

    op.drop_table('guardians')
    op.drop_table('schools')
    # ### end Alembic commands ###
