"""add attendance records and absence events

Revision ID: 515b8f55b6ee
Revises: 4b5a42df95a7
Create Date: 2026-10-02 08:27:10.902603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515b8f55b6ee'
down_revision: Union[str, Sequence[str], None] = '4b5a42df95a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('present', 'absent')", name=op.f('ck_attendance_records_status_valid')),
    sa.ForeignKeyConstraint(['school_id', 'student_id'], ['students.school_id', 'students.id'], name=op.f('fk_attendance_records_school_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('school_id', 'id', name='uq_attendance_records_school_id_id'),
    sa.UniqueConstraint('school_id', 'student_id', 'attendance_date', name='uq_attendance_records_school_student_date')
    )
    op.create_table('absence_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_record_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('correction_notice_owed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'cancelled', 'dialing', 'completed', 'failed')", name=op.f('ck_absence_events_status_valid')),
    sa.ForeignKeyConstraint(['school_id', 'attendance_record_id'], ['attendance_records.school_id', 'attendance_records.id'], name=op.f('fk_absence_events_school_id_attendance_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_absence_events')),
    sa.UniqueConstraint('attendance_record_id', name=op.f('uq_absence_events_attendance_record_id'))
    )
    with op.batch_alter_table('absence_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absence_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_events_status'))

    op.drop_table('absence_events')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
