"""add call attempts and needs human status

Revision ID: a5c1e0c4ec1f
Revises: 0a011cbfb0bc
Create Date: 2026-10-04 07:47:59.455335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c1e0c4ec1f'
down_revision: Union[str, Sequence[str], None] = '0a011cbfb0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('absence_events', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_absence_events_status_valid'), type_='check')
        
        batch_op.create_check_constraint(
            op.f('ck_absence_events_status_valid'),
            "status IN ('pending', 'cancelled', 'dialing', 'completed', 'failed', 'needs_human')",
        )
        batch_op.create_unique_constraint('uq_absence_events_school_id_id', ['school_id', 'id'])
        
    op.create_table('call_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('absence_event_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('turn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("outcome IN ('completed', 'escalated', 'wrong_person', 'opted_out', 'call_later', 'incomplete')", name=op.f('ck_call_attempts_outcome_valid')),
    sa.CheckConstraint("status IN ('in_progress', 'finished')", name=op.f('ck_call_attempts_status_valid')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_call_attempts_attempt_number_positive')),
    sa.CheckConstraint('turn_count >= 0', name=op.f('ck_call_attempts_turn_count_not_negative')),
    sa.ForeignKeyConstraint(['school_id', 'absence_event_id'], ['absence_events.school_id', 'absence_events.id'], name=op.f('fk_call_attempts_school_id_absence_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_attempts')),
    sa.UniqueConstraint('absence_event_id', 'attempt_number', name=op.f('uq_call_attempts_absence_event_id'))
    )
    
    with op.batch_alter_table('call_attempts', schema=None) as batch_op:
        batch_op.create_index('uq_call_attempts_one_in_progress', ['absence_event_id'], unique=True, sqlite_where=sa.text("status = 'in_progress'"), postgresql_where=sa.text("status = 'in_progress'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # call_attempts goes first: it references absence_events.
    with op.batch_alter_table('call_attempts', schema=None) as batch_op:
        batch_op.drop_index('uq_call_attempts_one_in_progress', sqlite_where=sa.text("status = 'in_progress'"), postgresql_where=sa.text("status = 'in_progress'"))

    op.drop_table('call_attempts')

    # The old status list has no needs_human, so those rows become failed before it returns.
    op.execute("UPDATE absence_events SET status = 'failed' WHERE status = 'needs_human'")
    with op.batch_alter_table('absence_events', schema=None) as batch_op:
        batch_op.drop_constraint('uq_absence_events_school_id_id', type_='unique')
        batch_op.drop_constraint(op.f('ck_absence_events_status_valid'), type_='check')
        batch_op.create_check_constraint(
            op.f('ck_absence_events_status_valid'),
            "status IN ('pending', 'cancelled', 'dialing', 'completed', 'failed')",
        )
